### ISSUE TITLE
创建kube-state-metrics-deployment时出错，信息如下

### ISSUE THREAD

**Issue by huangfuyixiao** [xiaoping378/k8s-monitor#6]
Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
集群中的api-server配置文件中将serviceAccount去掉了，能给个不用安全认证的部署文件或者能说明下修改哪里可以不通过安全认证正常部署吗

**Comment by huangfuyixiao** [comment]
问题已解决，方法如下，
一、部署前开启serviceaccount
1、vi /etc/kubernetes/kube-apiserver 添加：
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"
KUBE_API_ARGS="--service_account_key_file=/tmp/service_account.key"

2、vi /usr/lib/systemd/system/kube-apiserver.service添加：
ExecStart=/usr/bin/kube-apiserver    ${KUBE_LOGTOSTDERR}         \
                        ${KUBE_LOG_LEVEL}           \
                        ${KUBE_ETCD_SERVERS}        \
                        ${KUBE_API_ADDRESS}         \
                        ${KUBE_API_PORT}            \
                        ${NODE_PORT}                \
                        ${KUBE_ADVERTISE_ADDR}      \
                        ${KUBE_ALLOW_PRIV}          \
                        ${KUBE_SERVICE_ADDRESSES}   \
                        ${KUBE_ADMISSION_CONTROL}   \
                        ${KUBE_API_ARGS}   
3、vi /etc/kubernetes/kube-controller-manager添加：
KUBE_CONTROLLER_MANAGER_ROOT_CA_FILE="--root-ca-file=/var/run/kubernetes/apiserver.crt"
KUBE_CONTROLLER_MANAGER_SERVICE_ACCOUNT_PRIVATE_KEY_FILE="--service-account-private-key-file=/tmp/service_account.key"
其中：/var/run/kubernetes/apiserver.crt为k8s默认生成的证书文件；
      /tmp/service_account.key为手动生成的证书文件，生成命令：openssl genrsa -out /tmp/service_account.key 2048

4、vi /usr/lib/systemd/system/kube-controller-manager添加：
ExecStart=/usr/bin/kube-controller-manager   ${KUBE_LOGTOSTDERR} \
                                ${KUBE_LOG_LEVEL}   \
                                ${KUBE_MASTER}      \
                                ${KUBE_CONTROLLER_MANAGER_SERVICE_ACCOUNT_PRIVATE_KEY_FILE} \
                                ${KUBE_CONTROLLER_MANAGER_ROOT_CA_FILE}

5、重启kube-controller-manager和kube-apiserver。
    systemctl daemon-reload  
	systemctl restart  kube-controller-manager 
	systemctl restart  kube-apiserver 
	
6、验证，执行kubectl get serviceaccount 会看到secret选项下面有值，即代表上述操作成功。
（以上操作可以解决serviceaccount开启后token自动生成问题）
二、借鉴博客http://blog.csdn.net/wenwst/article/details/76624019，生成rbac.yaml文件，文件内容如下，文件借鉴以上链接博客。
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
- kind: ServiceAccount
  name: kube-state-metrics
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  verbs: ["list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs: ["list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
  namespace: monitoring
（以上解决，连接api server，发现资源问题）

**Comment by xiaoping378** [comment]
:+1:

**Comment by xiaoping378** [comment]
建议你不要用这个项目了，很久没更新了。你可以参考下kargo，提供了一揽子解决方案，或者直接上openshift也行。
